when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test: &web_profiler_test
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            collect: false
            collect_serializer_data: true

when@test_cached: *web_profiler_test
